name: manage-azure-policy-1a5d4b0b
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Restrict_storage_account_firewall_rules_ed61fc43-b37b-4dfd-b690-8a646d4ea97f/**'
#      - .github/workflows/manage-azure-policy-1a5d4b0b.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_1a5d4b0b}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Restrict_storage_account_firewall_rules_ed61fc43-b37b-4dfd-b690-8a646d4ea97f/**
